### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by chengchengpei** [antlr/antlr4-tools#5]
I downloaded this repo and run `python setup.py install`. python is 3.10.8

then, I run `antlr4`, got the following errors
```
antlr4-tools % antlr4
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/antlr/v4/Tool, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

My java version
```
% java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
```

Any idea why? thanks

**Comment by ericvergnaud** [comment]
You need Java 11 to run the tool, but Java 8 is sufficient for the runtime

**Comment by parrt** [comment]
Thanks for responding, @ericvergnaud .   Yep, @chengchengpei please try with Java 11.
